spring:
  config:
    activate:
      on-profile: test
  devtools:
    add-properties: true
    #TEST
#  sendgrid:
#    api-key: ${SENDGRID_API_KEY}
#    from-email: huypqse@gmail.com
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true

openapi:
  service:
    api-docs: cinema-api # Ensure this key matches the Java class
    title: Backend API Document
    version: v1.1.0
    server: ${BACKEND_SERVICE:http://localhost:${server.port}/cinemahouse}   # Use an IP address when deploying to the cloud

