spring:
  config:
    activate:
      on-profile: dev
  devtools:
    restart:
      enabled: true  # Kích hoạt tính năng restart tự động

  main:
    allow-bean-definition-overriding: true
  mail:
      host: ${HOST_SMTP:DUMMY-HOST_SMTP}
      port: ${PORT_SMTP:DUMMY-PORT_SMTP}
      username: ${USERNAME_SMTP:DUMMY-USERNAME_SMTP}
      password: ${PASSWORD_SMTP:DUMMY-PASSWORD_SMTP}
      properties:
        mail:
          smtp:
            auth: true
            starttls:
              enable: true
#  elasticsearch:
#      uris: http://localhost:9200
  sendgrid:
    api-key: ${SENDGRID_API_KEY:DUMMY-SENDGRID_API_KEY}
    from-email: ${SENDGRID_FROM_EMAIL:DUMMY-SENDGRID_FROM_EMAIL}


  datasource:
      driver-class-name: org.postgresql.Driver
#      gán bieens moi truong nhan tu ben ngoai vao, bien nay bi null hoac k co gia tri mac dinh gan vao bien
      url: jdbc:postgresql://${DATABASE_HOST:localhost}:${DATABASE_PORT:15432}/cinemahouse
      username: ${DATABASE_USERNAME:sa}
      password: ${DATABASE_PASSWORD:12345}

    #  data:
    #    elasticsearch:
    #      repositories:
    #        enabled: true


  jpa:
      hibernate:
        ddl-auto: update  # Hoặc 'create-drop' tùy theo yêu cầu
      properties:
        hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect


outbound:
    identity:
      client-id: ${OUTBOUND_IDENTITY_CLIENT_ID:DUMMY-OUTBOUND_IDENTITY_CLIENT_ID}
      client-secret: ${OUTBOUND_IDENTITY_CLIENT_SECRET:DUMMY-OUTBOUND_IDENTITY_CLIENT_SECRET}
      redirect-uri: ${OUTBOUND_IDENTITY_REDIRECT_URI:DUMMY-OUTBOUND_IDENTITY_REDIRECT_URI}

jwt:
    signerKey: ${JWT_SIGNERKEY:DUMMY-JWT_SIGNERKEY}
    valid-duration: ${JWT_VALID_DURATION:DUMMY-JWT_VALID_DURATION}
    refreshable-duration: ${JWT_REFRESHABLE_DURATION:DUMMY-JWT_REFRESHABLE_DURATION}


#integration:
#    minio:
#      access-key: admin
#      secret-key: admin@2025
#      url: http://localhost:9000 # Updated for Docker

payment:
  vnpay:
    tmn-code: ${VNPAY_TMN_CODE:DUMMY-VNPAY_TMN_CODE}
    secret-key: ${VNPAY_SECRET_KEY:DUMMY-VNPAY_SECRET_KEY}
    init-payment-url: https://sandbox.vnpayment.vn/paymentv2/vpcpay.html #cai link nay de fe redirect sang url nay, lien ket do tao ra payment request
    return-url: https://dev.cinemahouse.com/order/%s/status #khi giao dich xong thi redirect lai sang trang minh
    timeout: 15 # in minutes


logging:
    level:
      org:
        hibernate:
          SQL: DEBUG
          type:
            descriptor:
              sql:
                BasicBinder: TRACE

      springframework.security: DEBUG
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
      enabled: true
openapi:
  service:
    api-docs: cinema-api # Ensure this key matches the Java class
    title: Backend API Document
    version: v1.1.0
 # Use an IP address when deploying to the cloud
    server: http://localhost:${server.port}