server:
  port: 9090
spring:
  application:
    name: cinemahouse-service
  profiles:
    active: @spring.profiles.active@
management:
  endpoints:
    web:
      exposure:
        include: '*'  # Đã mở tất cả endpoints, nhưng có thể chỉ định cụ thể
  endpoint:
    prometheus:
      enabled: true  # Bật endpoint /actuator/prometheus
  prometheus:
    metrics:
      export:
        enabled: true


